#Config DataBase
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital_management
    username: postgres
    password: vich1103
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HospitalManagementAPI
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 2000
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update #update #create-drop
    show-sql: true
